num_nodes: 358
in_steps: 12
out_steps: 12

train_size: 0.6
val_size: 0.2

time_of_day: True
day_of_week: True

lr: 0.003
weight_decay: 0.0005
lr_decay: True
milestones: [16, 32, 48]
lr_decay_rate: 0.1
batch_size: 64
max_epochs: 60
early_stop: 20
use_cl: False
cl_step_size: 2500

model_args:
  num_nodes: 358
  in_steps: 12
  out_steps: 12
  input_dim: 3
  output_dim: 1
  embed_dim: 10
  hidden_dim: 32
  cheb_k: 2
  num_heads: 4
  num_layers: 1
  dropout: 0.1
  c: 10


